---
title: "ParagraphClassification"
author: "Rohan Khollamkar"
date: "7 April 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,eval = TRUE,warning = TRUE,error = TRUE,message = TRUE,cache=FALSE, tidy=FALSE, fig.path='figures/')
```

**Library**   
```{r load_libs, echo=T}
library(dplyr)
library(stringr)
library(ggplot2)
library(Rstem)
```

**Load a text paragraph**
```{r text_data, echo=T}
words <- readLines("cybersecurity blog.txt")
head(words)
```

**make a vector of words**
```{r word_vectors, echo =T}
vcsWords <- str_split(words, pattern = " ")
vcsWords <- unlist(vcsWords)
head(vcsWords,10)
```

**Clean all words**
```{r clean_words, echo =T}
# convert to lower-case
vcsWords <- str_to_lower(vcsWords)

# remove punctuations
vcsWords <- str_replace_all(vcsWords,pattern="[[:punct:]]", "")

# remove numbers
vcsWords <- str_replace_all(vcsWords,pattern="[[:digit:]]", "")

# remove spaces
vcsWords <- str_replace_all(vcsWords,pattern="[[:space:]]", "")

# remove special chars
vcsWords <- str_replace_all(vcsWords,pattern="[~@#$%&-_=<>]", "")

# filter out null values
vcsWords <- vcsWords[vcsWords != ""]

head(vcsWords,100)

```

**make dataframe of words**
```{r word_data_frame, echo=T}
word.frame <- data.frame(words = vcsWords)
#word.frame$words <- as.character(words)
head(word.frame,10)
```

**Calculate frequency of words**
```{r word_frequency, echo =T}
word.frame <- word.frame%>% 
              group_by(words)%>% 
              summarise(Freq = n())%>%
              arrange(desc(Freq))
head(word.frame)
```

**make a word cloud**
```{r word_cloud,echo =T}
library(wordcloud)
wordcloud(word.frame$words[1:100],freq = word.frame$Freq[1:100],random.order = F,max.words = 100,
          colors = brewer.pal(8,"Dark2"))
```

**Only important words to keep**
```{r important_words,echo =T}
# words with letter more than 2
word.frame <- filter(word.frame,str_length(words) > 2)
# remove stop_words
cmnwords <- c("all","also","and","any","are","but","can","cant","cry","due",
                 "etc","few","for","get","had","has","hasnt","have","her","here",
                 "hers","herself","him","himself","his","how","inc","into","its",
                 "ltd","may","nor","not","now","off","once","one","only","onto",
                 "our","ours","out","over","own","part","per","put","see","seem",
                 "she","than","that","the","their","them","then","thence","there",
                 "these","they","this","those","though","thus","too","top","upon",
                 "very","via","was","were","what","when","which","while","who","whoever",
                 "whom","whose","why","will","with","within","without","would","yet",
                 "you","your","yours","the","from","a","aa","of","it's","it","is","was","were")

word.frame <- filter(word.frame,!(words %in% cmnwords))

abusive.words <- c("arse","ass","asshole","bastard","bitch","bloody","bollocks","child-fucker","cunt","damn","fuck","goddamn","godsdamn","hell","motherfucker","shit","shitass","whore")

word.frame <- filter(word.frame,!(words %in% abusive.words))

head(word.frame,10)

```

**summarise again on frequency of words**
```{r word_frame,echo =T}
word.frame <- word.frame %>%
              arrange(desc(Freq))

head(word.frame,10)
```

**remove words with less frequency**
```{r sparse_words,echo=T}
word.frame <- filter(word.frame,Freq > 1)
tail(word.frame)
```

**word cloud of new dataframe**
```{r new_word_cloud, echo=T}
wordcloud(word.frame$words,freq = word.frame$Freq,random.order = F,max.words = 100,
          colors = brewer.pal(8,"Dark2"))
```



**load the file with words and their categories**
```{r csv_file,echo=T}
catgryWords <- read.csv("word_data1.csv",header = T,stringsAsFactors = F)
head(catgryWords)
```

**categorizing frparagraph**
```{r categorizing _para,echo=T}
high.freqwords <- as.character(word.frame$words)

matches <- catgryWords[catgryWords$words %in% high.freqwords, ]
matches

matches <- matches %>% group_by(type)%>%summarise(freq = n())%>%arrange(desc(freq))
matches

print(paste("paragraph belongs to ",as.character(matches[1,1]),"catageory"))
```
**



























